DELIMITER //

CREATE PROCEDURE ACTUALIZAR_CONFIGURACION(
    IN pParametro VARCHAR(255),
    IN pValor VARCHAR(255)
)
BEGIN
    UPDATE CONFIGURACION
    SET VALOR = pValor
    WHERE PARAMETRO = pParametro;
END //

DELIMITER ;

